### ISSUE TITLE
iChunUtil Render Bug

### ISSUE THREAD

**Issue by axlsjolund** [iChun/iChunUtil#102]
Hello there!

Hoping you can help with this one. So I'm using a custom private modpack and began experiencing a weird issue with the mod "Matter Overdrive". Specifically, rendering issues with phasers that also cause a variety of openGL errors for surrounding players. I reached out to the mod dev with the issue, and even gave him a copy of my pack to take a look. From his research he determined that it was an issue with iChunUtil rendering.

"It seem that iChunUtil is causing the error. They forgot to check if an item's icon is null."

He said it might be in relation to iChunUtil and using backtools. When backtools is removed, he found no problem. He also gave me a copy of the log specifically where it shows the issue for reference.

http://pastebin.com/J6h9ec0L

I'm using iChunUtil 4.2.2 (latest for 1.7.10). I know it is not the most current version overall, and the issue may very well be fixed in the newer version. However since majority of the mods I need are 1.7.10, that is where I am stuck. Is it possible to get a fix for this issue?

**Comment by Distjubo** [comment]
Its backtools fault. One of their items doesn't have an icon.

**Comment by Distjubo** [comment]
Does it only happen with Matter Overdrive?

**Comment by axlsjolund** [comment]
I've only noticed the problem when with Matter Overdrive phasers/phaser rifles, but is triggered by iChunUtil/BackTools combination as shown in the log. When back tools is removed issue is not present.

**Comment by shadowfacts** [comment]
This bug appears to be caused because there is no verification that an item's icon is not null. This bug was found using Matter Overdrive (the Phaser and Phaser Rifle don't have icons) but would theoretically also be a problem with any other item that used a custom item renderer instead of an icon.

**Comment by iChun** [comment]
By Minecraft code convention, no items should ever have a null IIcon, which
is why I never checked to see if it is null.

**Comment by iChun** [comment]
This, IIRC, changes in 1.8, however, so the check is (or, should be)
present in the 1.8 versions.

**Comment by axlsjolund** [comment]
Ok so it should be corrected in the 1.8 versions. But as I am still stuck with 1.7 because of mod support, is there a possibility for a hotfix for the 1.7 version?

I prefer to use the backtools mod if I can get a fix, but if not I can just remove it I suppose.

**Comment by iChun** [comment]
Most unlikely, sorry, again, this isn't something that is for me to fix.
