### ISSUE TITLE
[Suggestion] Config option to disable infection feature

### ISSUE THREAD

**Issue by RoyCurtis** [iChun/iChunUtil#105]
On our Infinity server, players have [started getting red and green flashes at random, along with potion effects](http://gfycat.com/EquatorialUnknownAfricanaugurbuzzard). After further testing, it was determined to be an "infection" spreading between players.

As we were unsure if this was a server bug, or even if it would cause long term harm to players, we tried to figure out where it was coming from. I [eventually asked the FTB community for ideas](https://www.reddit.com/r/feedthebeast/comments/3s099h/identifying_a_red_green_flash_with_poison_effects/). It was [eventually discovered that this is coming from iChunUtil](https://www.reddit.com/r/feedthebeast/comments/3s099h/identifying_a_red_green_flash_with_poison_effects/cwti3ij).

There have been complaints and confusion about this feature since six months ago:

* [Ramdon flash on ftb Infinity? ](https://www.reddit.com/r/feedthebeast/comments/33uo6a/ramdon_flash_on_ftb_infinity/)
* [Hey, anyone know what might be causing this weird effect? (Green flash and poison upon logging in)](https://www.reddit.com/r/feedthebeast/comments/36wc3c/hey_anyone_know_what_might_be_causing_this_weird/)
* [Poison effect when getting close to other players??](https://www.reddit.com/r/feedthebeast/comments/3fwhiu/poison_effect_when_getting_close_to_other_players/)

Personally, I think it is a cool feature. Nicely done! It did give us a good scare and plenty of jokes on voice chat :) But that said, I would like to propose that this feature become a configurable option, or at least be clarified in documentation.

My rationale for such an option is that it would:

* Save tick cycles on client and server calculating when to do an infection (in a real-time game with 200+ mods in a pack like Infinity, tick events are precious)
* Prevent issues for those with epilepsy or otherwise sensitivity to bright lights

**Comment by Mj11jM** [comment]
Good hunt, I messed up with my sharks comment apparently is what gave it away. I was messaging asking about the flashing lights as I was commenting to see if they could be a problem fixed without going public. Hopefully it doesn't become widespread knowledge so people can still have fun guessing. :)

**Comment by iChun** [comment]
Will be done in iChunUtil 1.9 and will be backported to up to 1.7.10 when TIv2 comes around.

**Comment by ExDomino** [comment]
How to disable this feature when letting know to the mod that the effect already happened?
My players begin to complain about this!
