### ISSUE TITLE
Disable random damage <kind of viral achievement>

### ISSUE THREAD

**Issue by ExDomino** [iChun/iChunUtil#122]
Hello,

I would like to disable for me and for my players that kind of viral achievement added by your mod, definitely. My played HATE this and we want to disable this useless and iritating feature.

If this setting cannot be disabled, what file I have to modifiy in order to make that the mod thing that the effect already has happened?

Thank you in advance!

**Comment by iChun** [comment]
It's been removed in 4.2.3
