### ISSUE TITLE
iChunUtil edits recipes in a non-main thread, causing IC2 to have a ConcurrentModificationException

### ISSUE THREAD

**Issue by Gaelan** [iChun/iChunUtil#136]
[This line](https://github.com/iChun/iChunUtil/blob/1.10/src/main/java/me/ichun/mods/ichunutil/common/iChunUtil.java#L161) is called by PacketSession, which does not run on the main thread.

[Crash Report with IC2's CME](https://github.com/iChun/iChunUtil/files/676439/crash-2016-12-28_15.46.25-client.txt)
[Crash Report with Aroma1997's mod for debugging this issue, showing that iChunUtil is responsible](https://github.com/iChun/iChunUtil/files/676440/crash-2016-12-28_16.31.41-client.txt)

**Comment by Gaelan** [comment]
Side note: it's a bit weird that iChunUtil needs to be on the client and server, even if the only iC mod in the pack is GooglyEyes, because iCUtil itself adds the compacted porkchop.

**Comment by Aroma1997** [comment]
This can be solved by using
`Minecraft.getMinecraft().addScheduledTask(Callable<V>)`
where the Callable is an Object (or a Lambda Expression) of what you want to do.

**Comment by iChun** [comment]
Yeah I will fix when I can. I've recently been brought aware of a couple of
issues caused by the separate threads between client and network that I
neglected to take into consideration. Currently out of the country though
so it'll be in January that I'll be able to fix this.

**Comment by iChun** [comment]
Fixed. Will be out in 6.2.1 - https://github.com/iChun/iChunUtil/commit/70b50514b8ae44f0a9b6a941b007f0fe2fb4c074
