### ISSUE TITLE
ThreadGetResources failes becaues of invalid URL

### ISSUE THREAD

**Issue by ichttt** [iChun/iChunUtil#144]
The URL for the download is still set to be https://raw.githubusercontent.com/iChun/iChunUtil/1.10/src/main/resources/assets/ichunutil/mod/patrons.json, while the 1.10 branch has been deleted

**Comment by iChun** [comment]
Whoooooooooops

**Comment by ichttt** [comment]
Closed by 37e7547323b3186384492e5db4f70b9247b57233
