### ISSUE TITLE
Can't clear the alert message mod V1.10.2-6.3.2

### ISSUE THREAD

**Issue by scalda** [iChun/iChunUtil#146]
Hi @iChun,

I am doing the next update to the FoolCraft mod pack, I have updated the ichunutil mod as it was needed for portal gun. 

and my problem is for the life of me, i can't get rid of the alert box that comes up on the main screen?

<img src=https://i.gyazo.com/c84eac3a546b4df33434e3913c494dd3.png>

Any ideas would be great?

Regards

Scalda

**Comment by shanecrosby** [comment]
I am also experiencing this. I tried changing the .cfg file, even trying to find the associated code inside the .jar (although I don't know java so gave up on that pretty quickly). Given that it is assumed you accept the EULA when downloading the mod, I don't see the point in requiring users to acknowledge it in-game as well. I don't know of any other mods that do that.

**Comment by anotyp** [comment]
This is a one time message. It  will display only once after an update. Then, it will be gone forever (or at least until the next update).

**Comment by FSDel** [comment]
I am also receiving this problem.
I have relaunched the client many times.
I have tried changing the EULA setting in the config file to true and 1...

It still doesn't seem to make the popup go away. Clicking the OK button does nothing :(

**Comment by FSDel** [comment]
I also can't "Click here" to get to the iChunUtils key binds... problem with detecting mouse click?

I am using Java 1.8.0_131-b11, windows 10 64-bit.
iChunUtil-1.10.2-6.3.2

**Comment by JzJad** [comment]
Yeah seem's there is something causing this I have players on my pack complaining about it all the time yet it only affects some people.

**Comment by shanecrosby** [comment]
It started working on one of my computers, but the other one still has the same problem.

**Comment by AlphaKintari** [comment]
Also having this issue. Craft of the Titans Pack.  Server config is set to TRUE, but the EULA screen does not seem to detect the OK, when clicking.  Another computer seems to be just fine.  I noticed that the working computer, the EULA was in the center top of the screen, but on the non-working version it was at the right - like pictured in @scalda 's screenshot.  Both computers are in different screen resolutions, so possibly that could be related.

**Comment by iChun** [comment]
I couldn't figure out the issue for this but I've added a timer that times out the message and you can also hit the enter/return keys to close the window. 

Sorry for the inconvenience, folks. Gonna pop an update for this soonish, version 6.4.0
