### ISSUE TITLE
iChunUtil - Crash upon launch

### ISSUE THREAD

**Issue by Goldenschmidt** [iChun/iChunUtil#147]
Hello fellow gamers.

I got a problem with the iChunUtill API.
Every time I try to launch minecraft, it just crashes just before going through tier 2 of the forge loading screen.
As for the details:
I'm using the 1.10.2 version of minecraft, on a windows 10 computer, running 64x bit.
I never got to create a world with this mod, as it crashes while loading the files.
Else, yes I play mix of Multiplayer and Singleplayer, but I only use this in Singleplayer.
Other mods? No. The only mods that's in the mods folder is: 
iChunUtil-1.10.2-6.3.2.jar 
I don't know if it's because I need a mod, like PortalGun or something.
I tried to search for ForgeModLoader-client-0.log and ForgeModLoader-server-0.log, but the only one existing was with minecraft Version 1.6.4, so it's outdated.
The only log I can give you about the crash, is the crash report. Please don't sue me for this, but that's all I got: [Crash-Report](https://www.pastebin.com/Qt0Rbzje)
I even tried with the PortalGun mod on: PortalGun-1.10.2-6.0.1.jar
I also crashed with that one: [Crash-Report](https://www.pastebin.com/6Xz12xcc)

What is going on?!

Please help me. I'll help you as well to solve this problem.

- Goldenschmidt

**Comment by ichttt** [comment]
I think it is a bug in forge that has been fixed in forge version 2182. Update to latest forge
