### ISSUE TITLE
Second Hitbox iChunUtil-1.10.2-6.4.0

### ISSUE THREAD

**Issue by essemX** [iChun/iChunUtil#150]
with iChunUtil-1.10.2-6.4.0 you get a second hitbox (F3+B) and it may causes issues with other mods

**Comment by iChun** [comment]
It's just a clientside entity that's attached to the player and not
collidable or pushable. I use it for rendering certain things and it's been
on the mod for a very long time without anyone having issues, so it should
be fine.

**Comment by essem2** [comment]
isn't it more efficient to just add the hitbox when its needed and not all the time? its just a bit confusing that you always see a hitbox inside you when you want to see other hitboxes.
