### ISSUE TITLE
Been 22 days still can't get rid of EULA  message trying to play foolcraft.

### ISSUE THREAD

**Issue by robertm1771** [iChun/iChunUtil#151]
No amount of time seem to hit this "timeout" that was added for a message that is really not needed. Making people agree to things like this is not legally binding without making it available at the time they agree. This is a silly and not needed message in the first place. Also can you provide a link on your website I looked for it over there and could not locate the EULA you say should be there. 

This seems like a way to make sure people know your mod is in use, and not a message to be sure people agree to an EULA that they can't seem to find easily. I found the GNU v3 listed here on this site.

**Comment by iChun** [comment]
Version?

**Comment by robertm1771** [comment]
Had to manually update version that comes with foolcraft. Maybe this will help the next guy.
