### ISSUE TITLE
Ask miscellaneous :) 

### ISSUE THREAD

**Issue by kizza5161** [iChun/iChunUtil#156]
Hi. I'm using your Streak, it's very good. I have some ideas for a new mod version (actually I need it), it helps players find a certain coordinates easier by following the instructions. Can you help me create it?

I can pay for it and you have the right to publish it for everyone. I will detail when you are interested in it.

 

>  Sorry for my english.

**Comment by iChun** [comment]
No thanks, I don't do paid mods nor have the time for them at the moment. Sorry.
