### ISSUE TITLE
Main Menu Graphical Issue on Intel based GPU

### ISSUE THREAD

**Issue by Pacguy64** [iChun/iChunUtil#157]
Having just iChunUtil-1.10.2-6.3.2 installed and nothing else brings back a graphical issue that seems to have been fixed in Forge itself. Some rough info can be read on it in the [Forge EAQ](http://www.minecraftforge.net/forum/topic/20-rules-and-eaq-read-first-or-you-will-get-banned/). I've tried to apply the recommended fix (despite running the current recommended Forge, 12.18.3.2185 for MC 1.10.2), with no results. Some other forum posts suggest that this might be a problem caused by using an old Intel integrated graphics card, which I happen to be using. Here's some info on my PC:

Operating System: | Windows 7 x64
Processor/CPU: | Intel(R) Core(TM)2 Duo CPU T6400 @ 2.00GHz 2.00GHz
Video Card/GPU: | Mobile Intel(R) GMA 4500MHD
Memory/RAM: 3 GB (2.87 usable)

and here's a txt file with my games output log: 
[outputlog.txt](https://github.com/iChun/iChunUtil/files/1480851/outputlog.txt)

A quick fix would be appreciated, I'm very hype for some of your new mods, and this computer is all I have...

**Comment by iChun** [comment]
I haven't really seen the logs but can you post some screenshots?

**Comment by Pacguy64** [comment]
![capture](https://user-images.githubusercontent.com/19475746/32936284-8676530a-cb28-11e7-9d03-25bf27b192f1.PNG)

The issue continues even when changing window sizes. The corner is animated, and when I attempt to click where the buttons _should_ be, I hear menu sounds, although I can't tell what's happening...

**Comment by iChun** [comment]
Can you try turning off stencils in the config and reporting back?

**Comment by iChun** [comment]
I've also just noticed that your system is somewhat ancient 😐

I'm hoping turning off stencils would fix it. Old systems are known not
work with stencils... I didn't think anyone still played current day
Minecraft on systems that old.

**Comment by Pacguy64** [comment]
That appears to have done it! Thanks for the quick fix :3
