### ISSUE TITLE
[1.12.2] 'O' options hotkey

### ISSUE THREAD

**Issue by Robijnvogel** [iChun/iChunUtil#161]
I know this was the way you could get to the iChun mods options.
Both in the PiP and iChunUtil configs it says to "Go to the options page and hit O to show other options."

In 1.12.2, this does not seem to work for me at the moment.
I made sure that none of the controls in Minecraft's Vanilla Controls menu are mapped to "O", but I can't seem to open your options menu in this version of Minecraft. I tried hovering my mouse pointer over various regions of the Options menu, including but not limited to buttons.

I forced a crash for the ease of sharing my setup's information:
https://pastebin.com/hbEYLFir

- [ ] Make it work again. If some other mod must be the cause, I'd like to test this for you. :)

- [ ] [Suggestion] Register your hotkeys in Minecraft's Controls menu, like 99% of other mods do.

- [ ] Add to the text in the config file(s) that you should be able to "click on the bottom right (on the text) in the controls menu" to open the config GUI as well.

**Comment by iChun** [comment]
Are you using the default QWERTY keyboard layout? If you're not you should
be able to click on the bottom right (on the text) to open the config GUI
instead

**Comment by iChun** [comment]
I've said it before and I'll say it again. I'm using a different config GUI
because my keybinds vary slightly from MC's. I added modifiers before they
existed for MC and I also listen for when the key is released.

The last time I checked what forge had done I remember thinking that it
still wasn't viable for my uses just yet.

I don't remember why now but I might reevaluate this in the future. I think
it was because they don't accept multiple modifiers

**Comment by Robijnvogel** [comment]
I am using the default QWERTY keyboard layout.

What bottom right text do you mean. Oh, in the key binds menu. :o 
That is waaaaaay too well hidden.

**Comment by iChun** [comment]
Well you *were* looking for iChunUtil keybinds. Actually I think I removed
the 'O' keybind because I've moved setting mod configs to the mods list.

**Comment by iChun** [comment]
I don't really remember anymore heh, it's been too long.

**Comment by Robijnvogel** [comment]
Edited the OP of this issue, for what I think would be the easiest temporary fix for now.

**Comment by iChun** [comment]
In my defence, I think I basically just forgot to update the localisation

**Comment by iChun** [comment]
https://github.com/iChun/iChunUtil/commit/b485c9e6b09682567821765df242a0f7d733b06a

I've checked and MC+Forge keybinds still do not support multiple modifiers so my keybinds will be here to stay until then.

**Comment by Robijnvogel** [comment]
If you haven't fixed anything, I think you should not close this issue.
Unless you choose to not implement any of the three ideas I proposed.

But that is just my view on Github issues.

**Comment by iChun** [comment]
- Listening for the O in a keybinds menu is hazardous and unnecessary.  I am not going to do that.

- I've already expressed why I am not registering my keybinds the way other mods do it. 

- I've already updated the localisation which goes into the config to explain how to get to my own keybinds. 

Issue resolved, issue closed.

**Comment by Robijnvogel** [comment]
"I've already updated the localisation which goes into the config to explain how to get to my own keybinds."
You did not explicitly state this. I am glad you did. :D

Have a nice day!

**Comment by iChun** [comment]
I linked a commit which does so before I mentioned why I won't be using
forge keybinds

**Comment by Robijnvogel** [comment]
Sorry, I typically mention the issue in the commit, which puts it in the feed of the issue separately. Not the other way around.
I'm really sorry for overlooking that commit link.

**Comment by iChun** [comment]
Yeah I forgot to mention it that's why I had to put a link, heh. I normally
mention which issue as well.
