### ISSUE TITLE
Game Crashing When I add ichunutil to mod Folder

### ISSUE THREAD

**Issue by Dracyan** [iChun/iChunUtil#167]
I Am Using 52 other mods and when I add ichunutil to The Minecraft Mods Folder and open the game the game crashes and I'm Greeted with this

The game crashed whilst registering texture
Error: java.lang.OutOfMemoryError: Java heap space

**Comment by Pythonic-Rainbow** [comment]
@Dracyan  this is not iChun's problem,
just give more RAM to java
https://www.minecraftforum.net/forums/support/unmodified-minecraft-client/tutorials-and-faqs/1871637-tutorial-allocate-more-memory-for-minecraft
