### ISSUE TITLE
Strange crash...

### ISSUE THREAD

**Issue by Sunconure11** [iChun/iChunUtil#168]
https://pastebin.com/TdE7u60z

It appears to have been triggered by newer builds of forge on a server end.

**Comment by Pythonic-Rainbow** [comment]
+1 
https://pastebin.com/bm8Gc2HT

**Comment by FunnyC715** [comment]
I am having the exact same isuue

**Comment by CDAGaming** [comment]
Same Issue here, am looking into trying to find a fix for this. Though it wont be easy, as compiling IChunUtil seems to be quite a predicament

**Comment by CDAGaming** [comment]
Good News and Bad News:
Good News: This Issue only seems to effect 2622 and 2623
Bad News: ATM, I don;t have a fix. Only work around is to stick to forge build 2621 or below

**Comment by CDAGaming** [comment]
More Good News:
By sheer Luck, I have found a Temporary Fix for this, though I'll test more in the morning

**Comment by CDAGaming** [comment]
Should be fully fixed now with #171 . Working OK now on Forge 14.23.2.2622 & 2623 :D

**Comment by CDAGaming** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4783

Should be fixed once this is available to download :D

**Comment by iChun** [comment]
Bit late on this. This issue has been fixed by Forge in build 2624. Avoid 2622 and 2623.
