### ISSUE TITLE
1.12.2-7.1.4 crashes dedicated server Forge 1.12.2 build 2623

### ISSUE THREAD

**Issue by kreezxil** [iChun/iChunUtil#169]
Notes:
     looking for what appears to be client side classes

crash report:
https://gist.github.com/a9a80ed09e44b40cf1121e79d64d3b23

fml server latest:
https://gist.github.com/95b10e595073c75bbaf2ce3fc65fbec1

**Comment by iChun** [comment]
Bit late on this. This issue has been fixed by Forge in build 2624. Avoid 2622 and 2623.
