### ISSUE TITLE
me.ichun.mods.ichunutil.client.entity.EntityLatchedRenderer is hard on FPS

### ISSUE THREAD

**Issue by Seegras** [iChun/iChunUtil#172]
I've been using LagGoggles on my Modern Skyblock 3 Departed world; and the entry in general on top for the FPS scan (meaning, the functions mostly responsible for lowering the FPS) is 
me.ichun.mods.ichunutil.client.entity.EntityLatchedRenderer, with a huge lead.

For instance: 

> 5675 ns/F me.ichun.mods.ichunutil.client.entity.EntityLatchedRenderer 
>  167 ns/F BlackHoleTank
>   96 ns/F TileContResT2
> ...

Note that this is FPS-related, and not TPS. 

So I've been asking myself, could it be that either some mod is abusing this function; or that the function itself is implemented in a way to produce overhead? 

I tired to sift out the mods that use iChunUtil via https://github.com/daviddrysdale/jnm but that doesn't really work, or I'm missing something. But maybe you've got a good idea which mods use it.

This is obviously low priority, I just thought you might want to know.

**Comment by temp1029** [comment]
Also having this issue in MS3. When I try to transport to the entity, it says it no longer exists but the FPS lag still exists.

![image](https://user-images.githubusercontent.com/4396942/44630204-e70ce200-a927-11e8-8014-b93cc74cd8b5.png)

![image](https://user-images.githubusercontent.com/4396942/44630209-f12ee080-a927-11e8-80b5-a95c863d04ae.png)

**Comment by Andr0oS** [comment]
Also having the same problem, mine's at 13691 ns/F, EntityHat is my second-highest tho, at 4494 ns/F.
I've had limited success limiting this by turning off mobs spawning with hats.

**Comment by DoraTheExploder** [comment]
If anyone playing MS3 is still having this issue the mod can be removed completely from the install as it does not have any active dependents.

**Comment by iChun** [comment]
I'm not sure what's causing this issue but I have identified that I'm accidentally spawning new EntityLatchedRenderers when the game is paused so I've fixed that.

I've also added a new config to disable them spawning entirely (I hope), not a definitive solution but that'll come only in 1.13.

These changes will be in the 7.2.0 update of iChunUtil.
