### ISSUE TITLE
iChunUtil crashing upon loadup

### ISSUE THREAD

**Issue by gingermcgiggles** [iChun/iChunUtil#176]
Anytime I try to run the Direwolf20 pack it crashes as soon as it tries to load iChunUtil. I know that it's this mod because i built the pack from scratch to test which mods were/weren't working. Any ideas what could be causing this? It doesnt generate a crash report, so I unfortunately don't have one to post, it just gives me the error of "Java (TM) Platform SE binary has stopped working" which then gives me the option to check for solutions online, but when i try it just closes my client instead. Does anyone have any idea what's wrong or how I can fix this?

**Comment by iChun** [comment]
Are you still having this issue?
