### ISSUE TITLE
invisible entities 

### ISSUE THREAD

**Issue by Sunekaer** [iChun/iChunUtil#178]
Hey

When coming back from dimensions like Aroma mining dim or Deep Dark, entities becomes invisible sometimes just a few of them other times all them.
It only happens if you use the portal to get back from the dimension, not if you tp back.

tested with forge from 2760 up to 2768 and iChunUtil-1.12.2-7.1.4

[StoneBlock#160](https://github.com/Sunekaer/stoneBlock/issues/160)

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.

**Comment by Laike-Endaril** [comment]
> So the conflict is between codechickenlib and ichunutil. He’s an video of the issue plus showing mods https://github.com/Sunekaer/stoneBlock/files/2479323/invis-entities.mp4.zip Covers1624 says that “CCL doesn't touch EntityRendering”

A 1.12.2 user ran into this issue recently and I ended up debugging it for them (it was this issue).
I was able to reproduce the issue WITHOUT codechickenlib

You can easily reproduce the issue by loading up with only 2 mods
iChunUtil
The Aether (Aether Legacy)

1. Make a 2 block deep pit and spawn some sheep in it
2. Make an Aether portal (glowstone frame in nether portal shape, place water inside)
3. Travel to the Aether and back
4. Invisible sheep

Removing iChunUtil from the mix fixes the issue (in both the minimal test and the huge megapack the user had)

Edit: In case anyone decides to pursue this at some point, I suspect that this is a server-side entity tracker issue, as the "invisible" entities cannot nudge the player (nudging physics are done by the client, so if the entity doesn't transfer from server to client at all, they won't nudge you)
