### ISSUE TITLE
[1.12.2] Eternal, driver-side, system-consuming, memory leak when paired with Noppes's mods!

### ISSUE THREAD

**Issue by Paul17041993** [iChun/iChunUtil#180]
Some form of render code conflict between them causes the graphics driver to allocate more and more memory over time, to literal infinity. It affects at least MPM on my end, and CNPC as @notfood discovered here #177 .

It appears that ~2048KB is added every second for every custom entity, and other mods could be affected, though I have no worked out which mod is the one that keeps allocating the memory...

**Comment by Paul17041993** [comment]
<img width="959" alt="screenshot_345" src="https://user-images.githubusercontent.com/3912867/48180987-d7733600-e379-11e8-9388-5d9a449d386a.png">

**Comment by Paul17041993** [comment]
also affects better bunnies and llamas funnily enough, so the faulting/trigger code is shared between them in the same way that it is with MPM and CNPC...

**Comment by iChun** [comment]
Good news, I've spoken to Noppes and he's identified the issue on his end. It should be fixed in his mods from the next release.
