### ISSUE TITLE
World Portals - How do I create them?

### ISSUE THREAD

**Issue by X66Herobrine66X** [iChun/iChunUtil#190]
I was wondering how you create world portals like the ones shown in ichuns last blog post, the ones that didn't have the outline. Is there an nbt tag I can add to my portal gun to make it shoot world portals? Thanks.

**Comment by X66Herobrine66X** [comment]
Specifically I would like to know how to obtain these effects and items: https://www.youtube.com/watch?v=bxv0BXqn9Ns, https://www.youtube.com/watch?v=POxcLSLBAOI, https://gyazo.com/24e1098d509933b7b467abc06389acd4, and https://gyazo.com/5fc64db45a5929eb9c68a19512c0f613.

**Comment by creepinson** [comment]
I don't think portal guns has these features, but I could be wrong. I'll look at his source code to double check.
I would love to make a mod that creates these effects myself.

**Comment by creepinson** [comment]
The G.L.A.S.S mod is one that you might want that includes a similar feature although you can't walk through them

**Comment by iChun** [comment]
World Portals are a code library that helps GLASS and Portal Gun render other perspectives. GLASS is currently (afaik) the only project that is open source that uses World Portals to render another perspective. Code is required to create World Portals, in case you were wondering.
