### ISSUE TITLE
Stencils unsupported

### ISSUE THREAD

**Issue by Acelee2006** [iChun/iChunUtil#191]
whenever i start my forge launcher and it finishes loading the mods this is what it looks like.

https://user-images.githubusercontent.com/52809161/61099852-c19aa100-a431-11e9-937f-eaa2a2253d97.PNG

This is also only just with this mod and no other mods.

**Comment by Acelee2006** [comment]
I figured it out i disabled stencils in the config

**Comment by iChun** [comment]
Reopening cause I need to look into this in the future
