### ISSUE TITLE
minecraft Will be definitely crashes

### ISSUE THREAD

**Issue by AWDPWD** [iChun/iChunUtil#195]
when i installed this mod and open any worlds
minecraft Will be definitely crashes
I only installed this mod, nothing else
It just says 'Out of Memory!'
even if i gave 1020 MB of Memory
hope you can fix this bug :(
(
forge version 14.23.5.2807
minecraft version 1.12.2
mod version 1.12.2-7.2.1(7.2.1)
1020 MB(0.99 GB) of Memory for minecraft
8 GB(8192 MB) of Memory in my computer
Graphic has been set to minimum configuration
)
( I am not good at English ): )

**Comment by iChun** [comment]
Unfortunately modded minecraft nowadays requires a lot more RAM. You can try disabling stencils in the iChunUtil config to try and reduce the RAM usage but other than that if you're still running out of memory, you're pretty much out of luck.
