### ISSUE TITLE
Crash On preload ichunutil 7.2.2 forge 1.12.2

### ISSUE THREAD

**Issue by SSJBlueSonic54** [iChun/iChunUtil#200]
Somehow no crash report is generated

The launcher console says its bad video drivers

Is there any gpu / cpu requirements to IchunUtil to load?

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
