### ISSUE TITLE
iChunUtil crashing on boot

### ISSUE THREAD

**Issue by AtomicToast84** [iChun/iChunUtil#201]
Whenever iChunUtil begins initializing on the loading screen, everything locks up. The hammer stops moving, the progress bar progresses no further, then it just closes out. Then the Minecraft Launcher says that it crashed unexpectedly. Btw, if it helps, the mod I'm trying to use with it is G.L.A.S.S.
Thanks!

**Comment by AtomicToast84** [comment]
Also, would the game break if I installed more than one version of iCU?

**Comment by Trentonisaweesome** [comment]
i have the same problem! java just crashes and it happens everytime.

**Comment by xampie** [comment]
i am having the same problem but i have about 74 mods installd but i don't think that's the issue.
i have incleuded the crash report and log aswel.
please fix this isseu i would really appreciate it!

[latest.log](https://github.com/iChun/iChunUtil/files/4880901/latest.log)

[crash-2020-07-06_21.29.27-client.txt](https://github.com/iChun/iChunUtil/files/4880895/crash-2020-07-06_21.29.27-client.txt)

**Comment by iChun** [comment]
Woah, someone actually posted a crash log! Anyways @xampie your crash is caused by Chiseled Me ASM cause of a coremod failing, bring this over to their devs.

**Comment by iChun** [comment]
To the others: for future reference, it would help if a crash log was attached. Posting "my game crashed" isn't very helpful in identifying the cause
