### ISSUE TITLE
Question: 1.15 with Fabric?

### ISSUE THREAD

**Issue by RowanSkie** [iChun/iChunUtil#205]
So, I was actually wondering, how impossible would it be to update mods to 1.15, how impossible would it be to migrate to Fabric (which I know is really impossible but someone managed to put a WorldPortal-like mod through Immersive Portals), and likely would you update your mods to 1.15.

Just asking, because FAQ over the side doesn't have it yet.

**Comment by iChun** [comment]
I know this is a bit late of a reply, but a port to fabric would not be impossible, as to date they have enough to actually add what my mods would need, as well as Mixins to cover the rest.

However, I will not be doing it, I've only recently looked into Fabric modding (for a few days) and it is for my best interest that I remain primarily on Forge for the foreseeable future.
