### ISSUE TITLE
Game Crashes When I Load Into A World

### ISSUE THREAD

**Issue by clicktypeclick** [iChun/iChunUtil#206]
https://paste.dimdev.org/apirelumol.mccrash

**Comment by pitris90** [comment]
I have similiar issue with wtf out of memory problem... I updated my modpack and now ichunUtil is causing out of memory problem when loading into world or server

**Comment by pitris90** [comment]
my error log: https://paste.dimdev.org/yecekuresu.mccrash

**Comment by pitris90** [comment]
Okay, I tried to set page file size from fixed size to decide system page file size and error disappeared.. I had it on fixed size because of saving SSD lifetime... This error needs more investigation by author

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
