### ISSUE TITLE
Disable april fools prank

### ISSUE THREAD

**Issue by HugoZink** [iChun/iChunUtil#207]
Please add an option to disable this annoying april fool's "prank" in the config, or remove it outright. The snout is one thing, but the oinking sound is insane.

**Comment by xMrCaosx** [comment]
i'm agreed. I'm really angry with this stupid prank.
i was thinking a mod is making issues and i discoverd, again is IchunUtil making this troubles.

**Comment by 123mind123** [comment]
I second this.

**Comment by iChun** [comment]
Planned for a config in future versions. Will leave this issue open for other people checking in/reporting the same problem.

Sorry bout the oinking!

**Comment by alfieboris** [comment]
I was farmimg xp in my skeleton farm and then I started hearing those pig noises so I mined like 10x10x10 area to find that pig and then I went to check on the internet to see it was an April fools prank.
You got me.

**Comment by poeticwatcher** [comment]
Greetings, the date on my computer (as I feel that is relevant) is 03 Apr 2020, 08:44 EST ... I can't say with 100% certainty, but I imagine the server our friend has set up is running with the correct time.  My partner and I had the unfortunate experience of deciding to play minecraft on the 1st... And experienced this joke of yours.

For reference, we are all playing with the MC Eternal modpack.  And while the pig nose did indeed disappear after the 1st... THE PIG NOISES HAVE NOT! We have to resort to giving up an inventory space for... Maybe as long as we all play together?

Removing the joke or adding a config would be greatly appreciated. We have reported this to the modpack author as well. But as the internet appears to have rightly guessed this was your joke, I am reporting this issue to you as well.

**Comment by morerokk** [comment]
Thanks

**Comment by esotericist** [comment]
the fact this cannot be disabled is terrible. :(

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
