### ISSUE TITLE
world portals documentation

### ISSUE THREAD

**Issue by RCXcrafter** [iChun/iChunUtil#208]
I'm trying to make a simple world portals mod using your world portals library and I'm having some trouble figuring out how to use everything. The GLASS source code has been a big help so far but I can't quite figure everything out from there.
Is there some kind of documentation on how to use world portals? If not could you explain to me how the rendering of world portals is done? I figured out how to create two linked world portals that can teleport enetities, I've created a tile entity with a special renderer and I can tell I need to call WorldPortalRenderer.renderWorldPortal, but I'm not realy sure how and where to use it.

**Comment by iChun** [comment]
From my understanding, there have been other mods that have gone the route of ImmersivePortal's API. As World Portals has not been ported forwards yet anymore at this point and you're still interested in modding for more recent Minecraft versions, you could look into them instead.

As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
