### ISSUE TITLE
Config "buttonOptionsShiftOpensMods" is backwards

### ISSUE THREAD

**Issue by Andromander** [iChun/iChunUtil#210]
Minecraft: `1.15.2`
Forge: `31.2.9`
iChunUtil: `8.0.3`

According to this config option, it states `Override the Options button so pressing Shift when clicking it shows the Mods list.`. However, this description is incorrect.
Rather than clicking on the Options button to be taken to the Options screen, it takes you to the Mods menu. Holding shift is how to open the Options screen, instead.
On a similar note, the config does not appear to take effect. Regardless if this config is true or false, pressing the button still opens the Mod options and holding shift opens the Options screen. This was tested by the following:
- Change the option and apply changes without exiting the world
- Change the option, apply settings, exit world, then rejoin world
- Change the option, apply settings, restart game

This behaviour occurs with the Pause screen's Option button.

**Comment by iChun** [comment]
I don't remember if I fixed this or not at some point between this issue and the current 1.16 release D:

**Comment by iChun** [comment]
Before I forget again for the hundredth time, I've fixed this.
