### ISSUE TITLE
iChunUtil crash on splash screen, works occasionally

### ISSUE THREAD

**Issue by jojo0807** [iChun/iChunUtil#212]
Just like in the title, iChunUtil is crashing when it gets to the second stage of loading. Sometimes I can get it to load, but it's not consistent in the slightest. Since it's a loading crash, there's no actual crash report, but I'll post the logs here. 
For reference, I'm using the latest version of the mod for 1.12.2 on the latest version of forge for 1.12.2.

[debug.log](https://github.com/iChun/iChunUtil/files/5600973/debug.log)
[latest.log](https://github.com/iChun/iChunUtil/files/5600974/latest.log)
![screeniew](https://user-images.githubusercontent.com/73791646/100319904-674ea180-2f8e-11eb-92b0-c44cddf0ac1e.PNG)

**Comment by CristopherNavarro** [comment]
Broooo i have same error

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
