### ISSUE TITLE
[1.12.2 ] Pressing F5 resets item use 

### ISSUE THREAD

**Issue by stepsword** [iChun/iChunUtil#213]
If you have this mod installed and press F5 repeatedly, it'll interrupt any item use you're using. You can test this by holding right click on a vanilla bow and spamming F5 while it's charging but before it's reached max charge. This is different from vanilla behavior, which does not interrupt the usage (and causes unexpected side effects with mods which rely on onPlayerStoppedUsing).

**Comment by iChun** [comment]
Wait, so does this happen with 1.16.5 or not?

**Comment by iChun** [comment]
Closing all issues as iChunUtil is being reintroduced bit by bit in 1.18+
