### ISSUE TITLE
1.12.2 - Crash when loading world

### ISSUE THREAD

**Issue by stinky-lizard** [iChun/iChunUtil#214]
Sometimes, but not always, when loading into any world, the game crashes. I have VanillaFix, so I'm booted back to the title screen, but I have to restart the game to fix it. VanillaFix says iChunUtil is the culprit.

Here are the crash logs:
https://pastebin.com/dcj3U2t7

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
