### ISSUE TITLE
[Crash] there's a crash when i try to grab a ic2:te with GravityGun mod

### ISSUE THREAD

**Issue by gatoborrachon** [iChun/iChunUtil#217]
as the title says, when you try to grab an IC2's TileEntity, the game will crash with the following crash report:
https://pastebin.com/EUC53Xue

Versions:
Forge: 14.23.5.2854
IC2: 2.8.221-ex112
Gravity Gun: 7.1.0

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.

**Comment by gatoborrachon** [comment]
well, no problem, i understand it, thanks anyways
