### ISSUE TITLE
minecraft crashes when ichuntil is installed

### ISSUE THREAD

**Issue by remidu64** [iChun/iChunUtil#218]
here is the crash report
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CustomSkinLoader (CustomSkinLoader_Forge-14.12.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  XaeroMinimapPlugin (BetterPvP_21.4.5_Forge_1.12.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.8.jar)
  CoreModBase (Fasttrading-2.0-mc[1.12,1.12.2+].jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar)
  MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.12.1_Forge_1.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.140.0-SNAPSHOT-all.jar)
  HCASM (HammerLib-1.12.2-2.0.6.26.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 4/8/21 6:33 PM
Description: Initializing game

java.lang.NoClassDefFoundError: ft
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:249)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:520)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder$DefaultNetworkChecker.checkCompatible(NetworkModHolder.java:114)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder.check(NetworkModHolder.java:302)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder.testVanillaAcceptance(NetworkModHolder.java:332)
	at net.minecraftforge.fml.common.network.NetworkRegistry.register(NetworkRegistry.java:301)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:249)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:520)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder$DefaultNetworkChecker.checkCompatible(NetworkModHolder.java:114)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder.check(NetworkModHolder.java:302)
	at net.minecraftforge.fml.common.network.internal.NetworkModHolder.testVanillaAcceptance(NetworkModHolder.java:332)
	at net.minecraftforge.fml.common.network.NetworkRegistry.register(NetworkRegistry.java:301)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 151483984 bytes (144 MB) / 502091776 bytes (478 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                    | Source                                             | Signature                                |
	|:----- |:-------------------------------------------- |:-------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                                    | 1.12.2                     | minecraft.jar                                      | None                                     |
	| LC    | mcp                                          | 9.42                       | minecraft.jar                                      | None                                     |
	| LC    | FML                                          | 8.0.99.99                  | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                                        | 14.23.5.2854               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | xaerominimap_core                            | 1.12.2-1.0                 | minecraft.jar                                      | None                                     |
	| LC    | xaeroworldmap_core                           | 1.12.2-1.0                 | minecraft.jar                                      | None                                     |
	| LC    | com.elytradev.movingworld.common.asm.coremod |                            | minecraft.jar                                      | None                                     |
	| LC    | moresoundconfigcore                          | 1.0.0                      | minecraft.jar                                      | None                                     |
	| LC    | cubicchunkscore                              | 1.12.2-0.0.1184.0-SNAPSHOT | minecraft.jar                                      | None                                     |
	| LC    | uncraftingtable                              | 1.8-beta6                  | [1.12]UncraftingTable-1.8-beta6.jar                | None                                     |
	| LC    | actuallyadditions                            | 1.12.2-r151                | ActuallyAdditions-1.12.2-r151-2.jar                | None                                     |
	| LC    | applecore                                    | 3.4.0                      | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
	| LC    | aroma1997core                                | 2.0.0.2                    | Aroma1997Core-1.12.2-2.0.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | aroma1997sdimension                          | 2.0.0.2                    | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | attributefix                                 | 1.0.4                      | AttributeFix-1.12.2-1.0.4.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | codechickenlib                               | 3.2.3.358                  | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia                                     | 3.3.0                      | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
	| LC    | avaritiafurnace                              | 1.0.0                      | Avaritia_furnace-1.0.0-1.12.2.jar                  | None                                     |
	| LC    | backpacks16840                               | 3.5.8                      | backpacks+1.12.2+-+3.5.8.jar                       | None                                     |
	| LC    | baubles                                      | 1.5.2                      | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LC    | bettermagnets                                | 1.2                        | bettermagnets-1.2.jar                              | None                                     |
	| LC    | betterplacement                              | 1.0.0-1                    | BetterPlacement-1.0.0-1.jar                        | None                                     |
	| LC    | xaerobetterpvp                               | 21.4.5                     | BetterPvP_21.4.5_Forge_1.12.jar                    | None                                     |
	| LC    | bookshelf                                    | 2.3.590                    | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | bowinfinityfix                               | rv5.1                      | BowInfinityFix-1.12.2-rv5.1.jar                    | None                                     |
	| LC    | redstoneflux                                 | 2.1.1                      | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LC    | brandonscore                                 | 2.4.19                     | BrandonsCore-1.12.2-2.4.19.214-universal (1).jar   | None                                     |
	| LC    | calculations                                 | 1.1.0                      | Calculations-1.12-1.1.0.jar                        | None                                     |
	| LC    | ccm                                          | 1.0                        | ccm-1.0.jar                                        | None                                     |
	| LC    | ctm                                          | MC1.12.2-1.0.2.31          | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LC    | jei                                          | 4.16.1.302                 | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LC    | chisel                                       | MC1.12.2-1.0.2.45          | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LC    | chiselsandbits                               | 14.33                      | chiselsandbits-14.33.jar                           | None                                     |
	| LC    | classicbar                                   | @VERSION@                  | classicbar-0.5.4.jar                               | None                                     |
	| LC    | clumps                                       | 3.1.2                      | Clumps-3.1.2.jar                                   | None                                     |
	| LC    | cofhcore                                     | 4.6.6                      | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LC    | cofhworld                                    | 1.4.0                      | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LC    | colytra                                      | 1.2.0.4                    | colytra-1.12.2-1.2.0.4.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | crafttweaker                                 | 4.1.20                     | CraftTweaker2-1.12-4.1.20.618.jar                  | None                                     |
	| LC    | ctgui                                        | 1.0.0                      | CraftTweaker2-1.12-4.1.20.618.jar                  | None                                     |
	| LC    | crafttweakerjei                              | 2.0.3                      | CraftTweaker2-1.12-4.1.20.618.jar                  | None                                     |
	| LC    | cubicchunks                                  | 1.12.2-0.0.1184.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar     | None                                     |
	| LC    | cubicgen                                     | 1.12.2-0.0.140.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.140.0-SNAPSHOT-all.jar    | None                                     |
	| LC    | cucumber                                     | 1.1.3                      | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LC    | customskinloader                             | 14.12                      | CustomSkinLoader_Forge-14.12.jar                   | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LC    | waila                                        | 1.8.26                     | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | darkutils                                    | 1.8.230                    | DarkUtils-1.12.2-1.8.230.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | movingworld                                  | 1.12-6.353                 | movingworld-1.12-6.353-full.jar                    | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@              | davincisvessels-1.12-6.355-full.jar                | None                                     |
	| LC    | thermalfoundation                            | 2.6.7                      | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LC    | draconicevolution                            | 2.3.27                     | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LC    | draconicadditions                            | 1.15.1                     | Draconic-Additions-1.12.2-1.15.1.39-universal.jar  | None                                     |
	| LC    | easyelytrato                                 | 1.1                        | easyelytrato_1.12-1.1.jar                          | None                                     |
	| LC    | elementalcreepers                            | v4.3.3.g5616356            | Elemental-Creepers-Redux-Mod-1.12.2.jar            | None                                     |
	| LC    | elenaidodge                                  | 1.13.2                     | elenaidodge-1.12.2-1.13.2.jar                      | None                                     |
	| LC    | hammercore                                   | 2.0.6.26                   | HammerLib-1.12.2-2.0.6.26.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | projecte                                     | 1.12.2-PE1.4.1             | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | expequiv                                     | 11b                        | ExpandedEquivalence-1.12.2-11b.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | mantle                                       | 1.12-1.3.3.55              | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LC    | materialispreload                            | 1.2.1                      | materialis-1.12.2-1.2.1.jar                        | None                                     |
	| LC    | tconstruct                                   | 1.12.2-2.13.0.183          | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LC    | extrautils2                                  | 1.0                        | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | fasttrading                                  | 2.0                        | Fasttrading-2.0-mc[1.12,1.12.2+].jar               | None                                     |
	| LC    | fluxnetworks                                 | 4.0.14                     | fluxnetworks-1.12.2-4.0.14-31.jar                  | None                                     |
	| LC    | geneticsreborn                               | 1.28                       | geneticsreborn-1.12-1.29.jar                       | None                                     |
	| LC    | getexpforeverything                          | 1.12.2                     | getexpforeverything-1.12.2.jar                     | None                                     |
	| LC    | gravelminer                                  | 6.1.2                      | GravelMiner_1.12.1-6.1.2.jar                       | None                                     |
	| L     | ichunutil                                    | 7.2.2                      | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| L     | continousmusic                               | 1.0.0                      | infinitemusic-1.12.2-1.0.0.jar                     | None                                     |
	| L     | infinity                                     | 0.14.2                     | Infinity-0.14.2.jar                                | None                                     |
	| L     | inftrading                                   | 1.0                        | inftrading_1.12-1.0.jar                            | None                                     |
	| L     | ironchest                                    | 1.12.2-7.0.67.844          | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| L     | ironfurnaces                                 | 1.3.5                      | ironfurnaces-1.3.5.jar                             | None                                     |
	| L     | lootoverhaul                                 | 1.2                        | LootOverhaul-1.2.jar                               | None                                     |
	| L     | lucky                                        | 7.6.0                      | luckyblock-1.12.2-1.jar                            | None                                     |
	| L     | lunatriuscore                                | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| L     | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| L     | materialis                                   | 1.2.1                      | materialis-1.12.2-1.2.1.jar                        | None                                     |
	| L     | mctsmelteryio                                | 1.2.63                     | MCTSmelteryIO-1.12.2-1.2.63.jar                    | None                                     |
	| L     | minemenu                                     | 1.6.11                     | MineMenu-1.12.2-1.6.11-universal.jar               | None                                     |
	| L     | mtrm                                         | 1.2.2.30                   | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
	| L     | refinedstorage                               | 1.6.15                     | refinedstorage-1.6.15.jar                          | None                                     |
	| L     | moartinkers                                  | 0.6.0                      | moartinkers-0.6.0.jar                              | None                                     |
	| L     | morph                                        | 7.2.0                      | Morph-1.12.2-7.2.1.jar                             | None                                     |
	| L     | mousetweaks                                  | 2.10                       | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| L     | uteamcore                                    | 2.2.5.147                  | u_team_core-1.12.2-2.2.5.147.jar                   | None                                     |
	| L     | musicplayer                                  | 2.1.1.113                  | music_player-1.12.2-2.1.1.113.jar                  | None                                     |
	| L     | mychunkloader                                | 1.12.2-01                  | MyChunkloader-1.12.2-01.jar                        | None                                     |
	| L     | mysticalagriculture                          | 1.7.5                      | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| L     | mysticalagradditions                         | 1.3.2                      | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
	| L     | naturescompass                               | 1.8.5                      | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| L     | currency                                     | 3.1.5                      | NeverEnoughCurrency-4.0.1.jar                      | None                                     |
	| L     | nodami                                       | 1.3.1                      | nodami-1.12.2-1.3.1.jar                            | None                                     |
	| L     | recipehandler                                | 0.13                       | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| L     | potioncore                                   | 1.9_for_1.12.2             | PotionCore-1.9_for_1.12.2 (1).jar                  | None                                     |
	| L     | reborncore                                   | 3.19.4.529                 | RebornCore-1.12.2-3.19.4.529-universal.jar         | None                                     |
	| L     | thermalexpansion                             | 5.5.7                      | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| L     | projecteintegration                          | 1.12.2                     | ProjectEIntegration-1.12.2-2.3.1.jar               | None                                     |
	| L     | projectex                                    | 1.2.0.40                   | ProjectEX-1.2.0.40.jar                             | None                                     |
	| L     | projectintelligence                          | 1.0.9                      | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| L     | randomarmormobs                              | 1.1                        | RandomArmorMobs-1.12.2-1.1.jar                     | None                                     |
	| L     | rebornstorage                                | 1.0.0                      | RebornStorage-1.12.2-3.3.4.85.jar                  | None                                     |
	| L     | redstonearsenal                              | 2.6.3                      | RedstoneArsenal-1.12.2-2.6.3.18-universal.jar      | None                                     |
	| L     | redstonepaste                                | 1.7.5                      | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
	| L     | refinedexchange                              | 2.1.1                      | refinedexchange-2.1.1.jar                          | None                                     |
	| L     | scalingfeast                                 | v1.6.1                     | scalingfeast-1.6.1.jar                             | None                                     |
	| L     | silentlib                                    | 3.0.13                     | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
	| L     | scalinghealth                                | 1.3.37                     | ScalingHealth-1.12.2-1.3.42+147.jar                | None                                     |
	| L     | solarflux                                    | 12.3.8                     | SolarFluxReborn_1.12.2-12.3.8 (1).jar              | None                                     |
	| L     | stackie                                      | 1.6.0.48                   | Stackie-1.12.2-1.6.0.48-universal.jar              | None                                     |
	| L     | swordblockingcombat                          | 1.2.3                      | SwordBlockingCombat-v1.2.3-1.12.2.jar              | None                                     |
	| L     | thermaldynamics                              | 2.5.6                      | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| L     | thermalinnovation                            | 0.3.6                      | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| L     | tinkersaddons                                | 1.0.7                      | Tinkers'+Addons-1.12.1-1.0.7.jar                   | None                                     |
	| L     | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769   | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| L     | torohealthmod                                | 1.12.2-11                  | torohealth-1.12.2-11.jar                           | None                                     |
	| L     | treechopper                                  | 1.2.4                      | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| L     | va                                           | 1.12.2-1.5.3               | va-1.12.2-1.5.5.jar                                | None                                     |
	| L     | wailaharvestability                          | 1.1.12                     | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| L     | wastelands                                   | 1.2.2                      | wastelands-1.2.2-universal.jar                     | None                                     |
	| L     | worldedit                                    | 6.1.10                     | worldedit-forge-mc1.12.2-6.1.10-dist.jar           | None                                     |
	| L     | xaeroworldmap                                | 1.12.1                     | XaerosWorldMap_1.12.1_Forge_1.12.jar               | None                                     |
	| L     | moresoundconfig                              | 1.0.4                      | moresoundconfig-1.0.4.jar                          | None                                     |
	| L     | additions                                    | 0.5.2                      | Additions-0.5.2 (1).jar                            | None                                     |

	Loaded coremods (and transformers): 
CustomSkinLoader (CustomSkinLoader_Forge-14.12.jar)
  customskinloader.forge.loader.LaunchWrapper
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
XaeroMinimapPlugin (BetterPvP_21.4.5_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.8.jar)
  brad16840.core.ClassTransformer
CoreModBase (Fasttrading-2.0-mc[1.12,1.12.2+].jar)
  com.dazo66.fasttrading.asm.MainTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1184.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
  ichttt.mods.moresoundconfig.asm.MSCTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
  c4.colytra.asm.ElytraTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
XaeroWorldMapPlugin (XaerosWorldMap_1.12.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
EECore (ExpandedEquivalence-1.12.2-11b.jar)
  com.zeitheron.expequiv.core.EETransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.140.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
HCASM (HammerLib-1.12.2-2.0.6.26.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7262' Renderer: 'Intel(R) HD Graphics 620'
	HammerCore Debug Information: 
		Dependent Mods:
			-Expanded Equivalence (expequiv) @ 11b

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 26.20.100.7262, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Tutorial_Resource_Pack
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7262
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

what do i do to fix this ?

**Comment by CristopherNavarro** [comment]
I have the same problem bro :/

**Comment by iChun** [comment]
As iChunUtil has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
