### ISSUE TITLE
versions.json missing

### ISSUE THREAD

**Issue by Macleykun** [iChun/iChunUtil#219]
Same as the other issue i reported, seems that this file was removed.
```
java.io.FileNotFoundException: https://raw.githubusercontent.com/iChun/iChunUtil/master/src/main/resources/assets/ichunutil/mod/versions.json
 at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
 at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
 at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
 at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
 at java.security.AccessController.doPrivileged(AccessController.java:946)
 at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:988)
 at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
 at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
 at java.net.URL.openStream(URL.java:1068)
 at me.ichun.mods.ichunutil.common.thread.ThreadGetResources.run(ThreadGetResources.java:67)
```
Latest forge on 1.12.2.

**Comment by Macleykun** [comment]
Tried to look into ichunutil.cfg if there's a way to not check the version as it only prints an error for now. But the cfg only allows to let or not let the user notify of an update. However this config has no effect because of the above issue.

Hope that this can be fixed

**Comment by iChun** [comment]
IIRC this only spits an error to the console, right? These are for much
older versions of the mod, and it's incredibly unlikely that I'll be
pushing any more updates for them. There shouldn't be any impact to
functionality since its just a version check.

**Comment by Macleykun** [comment]
True, I assumed that there weren’t going to be anymore updates for 1.12.2, but I hoped it wouldn’t be much effort to only remove this part of the code and push a (final) update for the mod on 1.12.2.

reason is that my error logging is relatively clean aside of a couple of errors, though i report them so it can be properly fixed.

If it might help, I’m also ok to look into this myself which code has to be removed to resolve the thrown error. If the pull is to your liking you only would need to push and publish.

I look forward to your opinion on the above!

**Comment by iChun** [comment]
It wouldn't be much effort to fix and update, all you need to do is to
prevent the version checker thread from starting.

However, I am not keen to push out an update for a version this old
especially if it doesn't fix anything the average user might spot. It might
give people the impression that I'm still supporting 1.12.2 which I've long
stopped supporting already.

You're more than welcome to modify the code yourself and make a build for
your own personal use. However, I neglected to make a legacy branch for
1.12.2 when I removed the master branch so you'll have to pull one of the
later branches and revert to the last commit for 1.12.2 and edit from
there.

**Comment by iChun** [comment]
Also, thank you for submitting this issue report, although I won't be
fixing it since it's for an older MC version.

Most users do not look through the console to spot errors and as a result,
some errors that should be fixed end up getting missed. It's good practice,
especially with modded Minecraft. I hope you keep it up and help out where
you can.

**Comment by Macleykun** [comment]
Sure no problem :) Thanks for your work and replies! Have a great weekend!
