### ISSUE TITLE
java.lang.ArrayStoreException: net.minecraft.client.gui.toasts.ToastGui$ToastInstance

### ISSUE THREAD

**Issue by aaronhowser1** [iChun/iChunUtil#224]
A player is getting this crash over and over again: https://gist.github.com/Milesman34/ee00e2d9d5bb252da361f8a5d043b618

They're playing [FTB University 1.16](https://www.feed-the-beast.com/modpack/ftb_university_1_16), which uses `iChunUtil-1.16.5-10.4.1`

**Comment by iChun** [comment]
I'll look into this in the future, they should be able to disable the Toast
manager override in the config as a workaround in the meantime.

**Comment by Spongman** [comment]
> they should be able to disable the Toast manager override

any clues as to how to do this?

**Comment by iChun** [comment]
Config file

**Comment by Spongman** [comment]
seriously?

**Comment by iChun** [comment]
... Yes?

The toggle is in the config file.

**Comment by iChun** [comment]
Either change the config ingame and restart the game or edit the config file (in the, you guessed it, the `config` folder) before starting the game.

**Comment by ukmcplyr** [comment]
Just to confirm, is the workaround mentioned above to set overrideToastGui to false in config/ichunutil.toml?

**Comment by iChun** [comment]
Yes.

**Comment by ukmcplyr** [comment]
Awesome, thank you!
