### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Sunekaer** [iChun/iChunUtil#225]
Log: https://gist.github.com/Sunekaer/b4a49e8d756f1642cde1467de8185e68
Seems to be random when it happens, for some when they join the game others in the middle of everything
1.16.5-forge-36.2.4
iChunUtil-1.16.5-10.4.1

**Comment by Spongman** [comment]
I'm seeing the same thing. FTB OceanBlock 1.2.0 multiplayer.

**Comment by Spongman** [comment]
Just happened to me again. I killed a rabbit with a hat.

**Comment by iChun** [comment]
#224
