### ISSUE TITLE
Shaders issue with The Betweenlands using iChunUtil.

### ISSUE THREAD

**Issue by MrRedstoneA1** [iChun/iChunUtil#226]
This is a bit of a rare issue that I'm sure nobody could have predicted or found out without these very specific circumstances. If The Betweenlands and iChunUtil are installed at the same time, the screen freezes in the dimension despite the modified shaders working before. The game continues to run, only the screen is frozen.

**Instructions to make the shaders work in The Betweenlands**

Download your desired shaders, it could be pretty much anything. I used Sildur's shaders, specifically the lite version. Open the shaders zip file and enter the _shaders_ folder. Make a new folder called world0. Move every single file into the world0 folder _EXCEPT_ the .properties files, the world1, world-1 and the lang folder. If you run into other issues, also make a new folder called world20 and leave it _empty._

What does this actually do?

The Betweenlands uses its own shaders to make some special effects happen. This automatically conflicts with any shaders that try to be active inside the dimension. What we're doing here is making the shaders only be active in the Overworld, Nether and End with those folders called world0, world1 and world-1.
Including the world20 folder but leaving it empty on purpose tells the shaderpack to load those shaders when inside the dimension, but because it's empty it won't load any shaders.

**How to reproduce:**

1. Install The Betweenlands.
2. Install the latest Optifine.
3. Install the shaders that have been slightly modified to work in The Betweenlands.
4. Verify that the shaders work and that The Betweenlands runs fine. I recommend making two worlds: in world one you're in the overworld, in world two you're in The Betweenlands. That way you can test both.
5. Install iChunUtil.
6. Start the game and load the world where you're in The Betweenlands.

**Result:**

The screen freezes in The Betweenlands. In the Overworld the shaders works fine. Removing iChunUtil fixes the shaders and The Betweenlands no longer freezes.

If you have any questions, please ask. If you need screenshots, unfortunately I have no clue how to include them. I don't use sites like imgur that let you host images. I hope this can help others having this problem and I hope it can be fixed.

**Comment by MrRedstoneA1** [comment]
I found out that going into the config file and disabling **stencils** fixes the issue. I don't know why that would cause shader issues, but that's a fix.

**Comment by iChun** [comment]
Closing all issues as iChunUtil is being reintroduced bit by bit in 1.18+, though I'll bear this in mind about stencils - most likely I'll still be using them in some mods, though MC has changed a lot since and has better Open GL support
