### ISSUE TITLE
Ichun util crashing

### ISSUE THREAD

**Issue by 145play145** [iChun/iChunUtil#227]
My forge version is latest, i tryed to launch by deleting all configs but it still crashing there crash log (yes i tryed without mods - it still crashing)

[crash-2021-10-14_06.58.00-fml.txt](https://github.com/iChun/iChunUtil/files/7342979/crash-2021-10-14_06.58.00-fml.txt)
.

**Comment by iChun** [comment]
Your crash log says you're crashing because tconstruct needs forge 36.2.4. That means you didn't try without mods properly and you're not on the latest forge like you said

**Comment by 145play145** [comment]
i'll try again without mods (my forge version is 36.2.8 btw)

**Comment by 145play145** [comment]
oh it worked look's like it's realy tinker's problem - sorry for bothering
