### ISSUE TITLE
[1.16.5] weird crash that seems to have been triggered by ichunutil

### ISSUE THREAD

**Issue by veccyboi** [iChun/iChunUtil#232]
tech specs: 
mc version: 1.16.5
ichunutil version: 10.6.1
googlyeyes version: 10.4.0
forge version: 36.2.39
my mods folder WITHOUT ichunutil:
![image](https://user-images.githubusercontent.com/85643556/208200995-7f6030f4-9b88-409e-b09c-2ee9781c8491.png)

**the problem:** before now, the combination of mods i have screenshotted (without ichunutil) have always loaded perfectly fine. however, i attempted to install the googlyeyes mod and ichunutil, and when i tried to load the game, it crashed and produced this crash report:
[crash-2022-12-15_19.55.23-fml.txt](https://github.com/iChun/iChunUtil/files/10249861/crash-2022-12-15_19.55.23-fml.txt)
and said that enderite mod was the issue, even though that same version of the enderite mod had always worked perfectly fine before. trying to load a second time even without ichunutil and googlyeyes resulted in the same issue.

to try to fix the issue, i tried deleting the config files for the enderite mod and reinstalling the mod jar file, but that caused another issue to occur: the game would still crash, but the crash reports produced would say: "Failed loading config file [mod name]-client.toml of type CLIENT for modid [mod name]"; this happened twice, first with mob battle, then with tiny redstone:
[crash-2022-12-15_20.09.31-client.txt](https://github.com/iChun/iChunUtil/files/10249865/crash-2022-12-15_20.09.31-client.txt)

[crash-2022-12-15_20.12.33-client.txt](https://github.com/iChun/iChunUtil/files/10249866/crash-2022-12-15_20.12.33-client.txt)

and when i checked the client configs for each of the affected mods, they were completely empty: 
![image](https://user-images.githubusercontent.com/85643556/208201552-b14b47eb-dabe-44e7-8ee2-af2c570c6c4f.png)

at this point i was unwilling to risk any more config files so i only have two of these kinds of crash reports to show you.
before i had installed ichunutil, no issues had occurred and i had not edited any config files at the time of the crashes.

help would be appreciated.

p.s.
i am submitting this bug report here as this only happened after i tried installing ichunutil, and mods like the enderite mod were completely fine beforehand
i am not sure if enderite mod did randomly break and i unfortunately do not have the time to check.

**Comment by veccyboi** [comment]
update: just tried loading again without enderite mod, ichunutil, or googlyeyes and the same thing happened again with the infernal expansion and additional guns config file: the contents get wiped; i delete the broken config files and relaunch the game, it crashes again; the previous mod's config file has been restored, but a new mod's has been wiped. it now does this regardless of if ichunutil or the enderite mod is present, it will randomly wipe a mod's config file, which has never happened before

**Comment by iChun** [comment]
This really is an odd one, I'm not sure why it's crashing either. I do have a random thought though, can you try disabling the toast override in iChunUtil? or maybe try disabling the stencil config as well if there is one. A few of the "riskier" stuff that iChunUtil does generally does have configs attached. 

Is there still disk space on your drive? If it's full it could be what's causing the blank configs, another possibility

**Comment by iChun** [comment]
Are you able to run with just iChunUtil installed and none of the other mods?

**Comment by veccyboi** [comment]
i just tried running the game with nothing but ichunutil and this happened:
[crash-2022-12-18_12.36.10-client.txt](https://github.com/iChun/iChunUtil/files/10254414/crash-2022-12-18_12.36.10-client.txt)
it couldn't find any mod files to wipe so it went for forge itself

**Comment by iChun** [comment]
Anything regarding the other stuff I mentioned?

**Comment by veccyboi** [comment]
i can't find anything that looks like it mentions stencils in the config file

**Comment by veccyboi** [comment]
most issues with stencils i've seen in other bug reports seem to occur in 1.12.2
are stencils specific to that version

**Comment by iChun** [comment]
Probably. Stencils are a thing in most iChunUtil versions that have portal gun.

Can you try updating your java as well? You're quite a number of versions behind. The configs are being wiped due to errors reading them but I'm not entirely sure why.

**Comment by iChun** [comment]
Safe to assume your build of iChunUtil is from curseforge?

**Comment by veccyboi** [comment]
yes

**Comment by veccyboi** [comment]
huh
i tried disabling the toast override and the game ran fine with just ichunutil but as soon as i add back in all my other mods the same thing happens again

**Comment by veccyboi** [comment]
and also is the stencils thing in ichunutil.toml?
![image](https://user-images.githubusercontent.com/85643556/208316171-03511308-3420-4e43-948b-81d586a529e8.png)
![image](https://user-images.githubusercontent.com/85643556/208316185-d3a6fbf0-b114-404f-aaf0-3a809278d1f4.png)
i might just be stupid but i don't see anything here that mentions stencils

**Comment by veccyboi** [comment]
and i just tried updating my java, and when i use command prompt it says i have "16.0.1", but the crash report still says i have "1.8.0_51"
[crash-2022-12-18_14.25.23-client.txt](https://github.com/iChun/iChunUtil/files/10254580/crash-2022-12-18_14.25.23-client.txt)

**Comment by veccyboi** [comment]
so i just tried deleting the whole config folder and letting the game make a new one and its fixed now...?
so one of my config files was messed up or something
