### ISSUE TITLE
[1.12.2] Unable to find 1.12 branch

### ISSUE THREAD

**Issue by IvvyDevMC** [iChun/iChunUtil#233]
Looking at the repos branches I am Unable to find the 1.12 Version of the Mod, while it exists on curseforge. Help / a Link would be appreciated

**Comment by iChun** [comment]
I didn't start splitting the source into branches by MC version until much
later. I'm afraid you'll have to go through the commit history until the
final commit on 1.12.2, it's there somewhere

**Comment by Jomosoto** [comment]
If anyone is also looking for it or if you maybe want to create the branches, here are the last commits before version changes ;) :
- 1.7.2: d8585890577d9e3b2476128a7fe7574d094cb67f
- 1.7.10: 07a32323e754989388049deb530d6dcabfbe35ed
- 1.8: 5b205fa100e3f8880986f6c2681d4a14bcc1996f
- 1.8.8: 45695f1a51b71913059d1522d6ead2184338a7f7
- 1.8.9: b57ed34cafe9263b5820eddaf03d03a4fb776400
- 1.9: 2e105b3d3b32c9a3f66b49eedee02b3e6f48021c
- 1.10.2: fd07cc3065748a8703cb995e94e9c3cc2c86b13d
- 1.12.2: 5cd18d371f70b798ceb3fabc6da4d72715322a88
