### ISSUE TITLE
[1.7.10] Please release on curseforge

### ISSUE THREAD

**Issue by DrComplainer** [iChun/iChunUtil#234]
Not coding issue but is it possible to put the 1.7.10 version onto curseforge? I would rather get it from the original person and I attempted compilation, but I'm a dunce.

**Comment by iChun** [comment]
![image](https://user-images.githubusercontent.com/2298444/227418960-bb17d71f-1b58-40c9-ab4d-9d454c28fc11.png)

![image](https://user-images.githubusercontent.com/2298444/227419004-a7bb6495-41dc-4bae-9da8-cac1dc45ef36.png)

![image](https://user-images.githubusercontent.com/2298444/227419070-b680823f-69f8-432d-b739-27702da28867.png)

![image](https://user-images.githubusercontent.com/2298444/227419165-d16da8df-8963-42db-be74-039f92b44f8b.png)

**Comment by iChun** [comment]
Good effort but totally off the mark 😂 

A lot of other mods will also have their old, old, oooold versions with the View All button on the Files page.
