### ISSUE TITLE
[1.21][Neoforge] Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [iChun/iChunUtil#235]
https://pastebin.com/Krbji737
iChunUtil-1.21-NeoForge-1.0.0

![image](https://github.com/user-attachments/assets/dbbe7bb3-ebd9-4336-ab90-9796180c4eec)

**Comment by MuteTiefling** [comment]
Same issue here. Adding my latest.log for reference

https://gist.github.com/MuteTiefling/b09600daa20069531853fa847840b228

**Comment by iChun** [comment]
Was fixed in iChunUtil 1.0.1
