### ISSUE TITLE
'O'ptions Bug

### ISSUE THREAD

**Issue by firestar115** [iChun/iChunUtil#59]
I have experienced that when on the options screen, unless you are hovering over a button, the menu does not trigger. (I usually press 'O' next to the text that says Hit 'O' For more options.)
It might be OS related, since LWJGL uses natives:
I use a Chromebook with [dschneid/crouton](https://github.com/dschneid/crouton)
Google Chrome: `40.0.2214.93 (Official Build)`
Revision: `c675f6a38876b473472b2581b549e6fa72caa11f`
Platform: `6457.83.0 (Official Build) stable-channel parrot`
Linux Version: `14.04 Trusty Tahr`
And if it makes a difference to you:
GL Version: `Mesa 3.0`

**Comment by iChun** [comment]
Issue should be fixed in the 1.8 version. You can click on that region to enter the options menu as well in that version (I don't know why I didn't think of it sooner)
