### ISSUE TITLE
Change packet execution

### ISSUE THREAD

**Issue by iChun** [iChun/iChunUtil#72]
https://github.com/iChun/iChunUtil/blob/master/src/main/java/us/ichun/mods/ichunutil/common/core/packet/mod/PacketPatrons.java

**Comment by iChun** [comment]
Possibly do an obf check while you're at it. https://github.com/iChun/iChunUtil/blob/master/src/main/java/us/ichun/mods/ichunutil/common/core/network/PacketChannel.java#L97

**Comment by Pr0kKiLlEr** [comment]
forge version:1.7.10
mods:BackTools-4.0.0, iChunUtil-4.1.0,MobAmputation-4.0.0,MobDismemberment-4.0.0
sorry if i post on wrong place i just don't know were to post this crash thing:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 10/3/2015 9:50 μμ
Description: Ticking screen

java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'MVdWAN30215'.
	at net.minecraft.scoreboard.Scoreboard.func_96512_b(SourceFile:206)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1573)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:100)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:12)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.scoreboard.Scoreboard.func_96512_b(SourceFile:206)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1573)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:100)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:12)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 13 total; [EntityClientPlayerMP['Pr0kKiLlEr'/10972, l='MpServer', x=-758,46, y=12,62, z=534,54], EntityOtherPlayerMP['Blossom1021'/10968, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityOtherPlayerMP['bountyhunter277'/10964, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityOtherPlayerMP['akdjde'/10640, l='MpServer', x=-757,16, y=11,00, z=536,25], EntityOtherPlayerMP['storm_E_sky'/10955, l='MpServer', x=-740,78, y=10,50, z=530,59], EntityOtherPlayerMP['MrDerpling'/9854, l='MpServer', x=-741,66, y=10,50, z=531,03], EntityOtherPlayerMP['DJRarity'/10071, l='MpServer', x=-742,03, y=9,50, z=539,28], EntityOtherPlayerMP['Vaughn1'/10822, l='MpServer', x=-740,47, y=10,50, z=532,41], EntityOtherPlayerMP['coolperson87'/9681, l='MpServer', x=-748,66, y=10,50, z=547,94], EntityOtherPlayerMP['cheatingconjurer'/10963, l='MpServer', x=-745,22, y=9,00, z=560,06], EntityOtherPlayerMP['ricky3styx'/9668, l='MpServer', x=-747,66, y=17,88, z=574,78], EntityOtherPlayerMP['PeterC555'/10952, l='MpServer', x=-758,47, y=9,00, z=565,47], EntityOtherPlayerMP['HERMIONE123'/10938, l='MpServer', x=-758,72, y=9,00, z=566,81]]
	Chunk stats: MultiplayerChunkCache: 75, 75
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-758,11,534), Chunk: (at 10,0,6 in -48,33; contains blocks -768,0,528 to -753,255,543), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 364924854 game time, 33217200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 63 total; [EntityClientPlayerMP['Pr0kKiLlEr'/10972, l='MpServer', x=-758,46, y=12,62, z=534,54], EntityOtherPlayerMP['Blossom1021'/10968, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityGib['unknown'/2, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/3, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/4, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['bountyhunter277'/10964, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityGib['unknown'/6, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/7, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/8, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['akdjde'/10640, l='MpServer', x=-757,16, y=11,00, z=536,25], EntityGib['unknown'/10, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/11, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/12, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['storm_E_sky'/10955, l='MpServer', x=-740,78, y=10,50, z=530,59], EntityGib['unknown'/14, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/15, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['akdjde'/10640, l='MpServer', x=-757,16, y=11,00, z=536,25], EntityGib['unknown'/16, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['MrDerpling'/9854, l='MpServer', x=-741,66, y=10,50, z=531,03], EntityGib['unknown'/18, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/19, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/20, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['DJRarity'/10071, l='MpServer', x=-742,03, y=9,50, z=539,28], EntityGib['unknown'/22, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/23, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/24, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['Vaughn1'/10822, l='MpServer', x=-740,47, y=10,50, z=532,41], EntityGib['unknown'/26, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/27, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/28, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['coolperson87'/9681, l='MpServer', x=-748,66, y=10,50, z=547,94], EntityGib['unknown'/30, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/31, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/32, l='MpServer', x=0,00, y=0,00, z=0,00], EntityItemFrame['entity.ItemFrame.name'/41, l='MpServer', x=-731,06, y=9,50, z=541,50], EntityItemFrame['entity.ItemFrame.name'/42, l='MpServer', x=-732,50, y=9,50, z=541,94], EntityItemFrame['entity.ItemFrame.name'/43, l='MpServer', x=-732,50, y=9,50, z=543,06], EntityItemFrame['entity.ItemFrame.name'/44, l='MpServer', x=-729,50, y=9,50, z=541,94], EntityItemFrame['entity.ItemFrame.name'/45, l='MpServer', x=-733,94, y=9,50, z=546,50], EntityItemFrame['entity.ItemFrame.name'/46, l='MpServer', x=-735,06, y=9,50, z=544,50], EntityItemFrame['entity.ItemFrame.name'/47, l='MpServer', x=-735,06, y=9,50, z=546,50], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=-732,50, y=9,50, z=548,94], EntityItemFrame['entity.ItemFrame.name'/49, l='MpServer', x=-734,50, y=9,50, z=550,06], EntityItemFrame['entity.ItemFrame.name'/50, l='MpServer', x=-732,50, y=9,50, z=550,06], EntityOtherPlayerMP['PeterC555'/10952, l='MpServer', x=-758,47, y=9,00, z=565,47], EntityGib['unknown'/52, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/53, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/54, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['HERMIONE123'/10938, l='MpServer', x=-758,72, y=9,00, z=566,81], EntityGib['unknown'/56, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/57, l='MpServer', x=0,00, y=0,00, z=0,00], EntityGib['unknown'/58, l='MpServer', x=0,00, y=0,00, z=0,00], EntityOtherPlayerMP['HERMIONE123'/10938, l='MpServer', x=-758,72, y=9,00, z=566,81], EntityOtherPlayerMP['ricky3styx'/9668, l='MpServer', x=-747,66, y=17,88, z=574,78], EntityOtherPlayerMP['Vaughn1'/10822, l='MpServer', x=-740,47, y=10,50, z=532,41], EntityOtherPlayerMP['PeterC555'/10952, l='MpServer', x=-758,47, y=9,00, z=565,47], EntityOtherPlayerMP['storm_E_sky'/10955, l='MpServer', x=-740,78, y=10,50, z=530,59], EntityOtherPlayerMP['coolperson87'/9681, l='MpServer', x=-748,66, y=10,50, z=547,94], EntityOtherPlayerMP['cheatingconjurer'/10963, l='MpServer', x=-745,22, y=9,00, z=560,06], EntityOtherPlayerMP['bountyhunter277'/10964, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityOtherPlayerMP['DJRarity'/10071, l='MpServer', x=-742,03, y=9,50, z=539,28], EntityOtherPlayerMP['Blossom1021'/10968, l='MpServer', x=-758,47, y=11,00, z=534,53], EntityOtherPlayerMP['MrDerpling'/9854, l='MpServer', x=-741,66, y=10,50, z=531,03]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"25ee8a1":1005) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 138082832 bytes (131 MB) / 258478080 bytes (246 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	iChunUtil{4.1.0} [iChunUtil] (iChunUtil-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MobAmputation{4.0.0} [MobAmputation] (MobAmputation-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce 9400 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
this is the crash report which i get while playing on a server(dunno what plugins this server has if that's the problem but it's mcorigins made by explodingtnt)

**Comment by iChun** [comment]
It's not my crash
