### ISSUE TITLE
Forge not recognizing iChunUtil

### ISSUE THREAD

**Issue by khionu** [iChun/iChunUtil#75]
When I load Minecraft, it's not recognizing iChunUtil. It says the minimum version it requires is 2.0.0.

Gyazo is an instant Screenshot->Share program, that is detected as a virus by ?Avast?, but I only heard of that once.
http://gyazo.com/0db109b131a5a10562ce095bd0102524 - Error
http://gyazo.com/5385a2e07f0a639657ffc481ee52440d - Contents of Mod Folder
http://pastebin.com/D3qwM55j - Client Log

**Comment by iChun** [comment]
Use the 2.X.X builds, not the 4/5.X.X builds

**Comment by iChun** [comment]
You're also going to break everything cause of the versions of mods you're grabbing anyways http://ichun.us/support/faq/mods/

**Comment by khionu** [comment]
Pardon? Nothing was broken. Forge never even loaded. I'm still trying to get my Mods picked out for my server (I have read your limitations/conditions for Modpacks. Server is staying at 1.7.10, unless you post an update saying otherwise, nevermind the fact that most of the mods I will be using are not ready for 1.8.x), and I ran into this issue.

Also, you say here that I should use the 2.x.x, but the link you shared in your last says I should use the 4.x.x for MC 1.7.10... can you clarify the contradiction?

**Comment by iChun** [comment]
I didn't look at your the mods you were trying, cause you said had gravity gun version 2.0.0. The FAQ is still right though. You need 4.X.X for MC 1.7.10 (which is what you're running according to your other mods)

**Comment by khionu** [comment]
Ok. Thank you for your time. Keep up the good work :)
