### ISSUE TITLE
iChunUtils crashing with only Forge on MC 1.8

### ISSUE THREAD

**Issue by syr-ark** [iChun/iChunUtil#79]
Trying to run only Forge (latest versions) and iChunUtils 5.3.0, minecraft crashes with the following log: http://paste.ee/p/uV44Z

Forge and Jar are installed by MultiMC. Minecraft loads successfully with only Forge.

**Comment by iChun** [comment]
34fded07-4e99-403b-9b9a-72e6933704ab.jar ? Why is that? the ATs aren't
launching but it looks like my mod jar is modified anyways. Can you try
getting a proper jar from my site, or could you try it without MultiMC?

**Comment by syr-ark** [comment]
I did get the jar directly from your site, but I have not yet tried without MultiMC. I'll try that and report back.

**Comment by syr-ark** [comment]
Well, I should have tried that first. I can confirm that something MultiMC was doing seems to be responsible. It works now that I manually copied the jar into my instance folder. Keygrip seems to be loading without problem, too. I'll have to make sure it functions still.
