### ISSUE TITLE
FZDS-induced lag

### ISSUE THREAD

**Issue by purpleposeidon** [iChun/iChunUtil#88]
Player found this: https://i.imgur.com/xkPHVVL.png
This seems to be the relevant source code: 
https://github.com/iChun/iChunUtil/blob/master/src/main/java/us/ichun/mods/ichunutil/client/patron/EffectTicker.java#L54
It doesn't like the secret client-side shadow world that FZDS adds.

Perhaps use a world unload event? Failing that, maybe use a list of WeakReferences or something.

(Oh, and setting zmin should help with the visible-blocks-in-front-of-Doors thing; gluPerspective will do the trick I think?)

**Comment by iChun** [comment]
Oh hmm, are you overriding theWorld field? Will look into sometime later.
