### ISSUE TITLE
Give iChun super pig powers

### ISSUE THREAD

**Issue by gudenau** [iChun/iChunUtil#92]
Kinda like apt-get's "super moo powers".

**Comment by CatDany** [comment]
Up!

**Comment by iChun** [comment]
<3


But no guys, this isn't an issue.

**Comment by gudenau** [comment]
Have to admit that it would be a neat easter egg. :-D

I do understand not wanting to spend time on something like this though.

**Comment by iChun** [comment]
What kinda ideas did you even have in mind?

**Comment by gudenau** [comment]
Just something silly like when you logon it says you have them.
